version: '2'

services:
  redis-db:
    image: redis:6.0.5-alpine3.12
    restart: on-failure
    networks:
      - redisnet

  redis-repo:
    image: szymonharabasz/redis-repo:1
    build:
      context: .
    depends_on:
      - redis-db
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - redisnet

networks:
  redisnet:
    driver: bridge